### ISSUE TITLE
Is it possible to build a binder with RStudio-latest?

### ISSUE THREAD

**Issue by mwouts** [binder-examples/r#33]
Hi,

Following the addition of the `quarto` format to Jupytext at https://github.com/mwouts/jupytext/issues/837, I'd like to add RStudio latest (& quarto) to my project's binder.

Is there an easy way to do so?

Thanks!

**Comment by choldgraf** [comment]
hmmm - I don't think so. This is where the RStudio version is defined:

https://github.com/jupyterhub/repo2docker/blob/5b5b759a4e3c74b372006f0c7492addc12f1bfee/repo2docker/buildpacks/_r_base.py#L8

I think the repo2docker project is the best place to ask about whether that can be extended.

**Comment by mwouts** [comment]
Interesting! Thank you @choldgraf :wave:

Also I see the https://github.com/binder-examples/apt_install/ repo, but it does not seem that I can use it to 1. download a `.deb` file from https://www.rstudio.com/products/rstudio/download/preview/ and then 2. install it, right?

**Comment by choldgraf** [comment]
I believe that it right though it has been a while since I've looked at that, I'd ask around in the repo2docker project

**Comment by cboettig** [comment]
I believe this was fixed by https://github.com/rocker-org/rocker-versioned2/pull/309

**Comment by mwouts** [comment]
Great! Thank you for letting us know. Do I need to do anything special? I just gave a try at https://mybinder.org/v2/gh/mwouts/jupytext/main and I still don't get `quarto`:

![image](https://user-images.githubusercontent.com/29915202/146924106-dcd3677d-e596-4606-b762-b0c31076a18e.png)
